name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Give the job a write-capable GITHUB_TOKEN (required by dependency submission)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    # Skip dependency submission on PRs from forks (token would be read-only -> 403)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Upload full dependency graph for better Dependabot alerts
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@df268dd1684fb95352aa463056e3cf41f9acb94b
